### ISSUE TITLE
Building more question types

### ISSUE THREAD

**Issue by binhle410** [fabiandev/angular2-quiz-app#11]
Do you have any plans for building more question types ?

**Comment by fabiandev** [comment]
Do you have any suggestions for more question types?
What I was thinking about was to make it easier to add new types and to add it to the readme.

**Comment by fabiandev** [comment]
I see, it would be a good idea to create more generic question types and to derive from them.
Any PR is very welcome, I won't have a lot of time to make enhancements right now, I'll try to keep the project up-to-date though.

There is a simple API provided by the built in server to get data from the Spotify API. Building the questions is part of the Angular app, which is intended, as this project was built to play around with Angular 2.

**Comment by fabiandev** [comment]
This feature is currently in progress (see #17 for updates ).
