### ISSUE TITLE
How to change background color?

### ISSUE THREAD

**Issue by augusterenoir** [fabiandev/angular2-quiz-app#16]
Hi guys,

this is rather a question than an issue. I want to change the background color of the entire app to white, so far I managed to change the color of the child componets of the app, but there is always teal color in the left and right of the app.

I would appreciate any kind of help, thanks!

**Comment by fabiandev** [comment]
`body` has the class `cyan` in [index.html](../blob/master/index.html#L19), which you can remove to get a white background. There's no need to change the component's background color individually. Also you may want to adjust the colors in [src/css/styles/loading-animation.less](../blob/master/src/css/styles/loading-animation.less).

**Comment by fabiandev** [comment]
@augusterenoir have you been able to adjust the colors as desired?

**Comment by augusterenoir** [comment]
@fabiandev It worked! Thanks so much for your quick reply and help! The issue can be closed. :)
